
import { Prompt, Guide, ProcessTemplate, Comment, User, ProjectContext } from './types';

export const CURRENT_USER: User = {
  id: 'user-1',
  name: 'Alex Developer',
  role: 'user',
  bookmarks: ['req-1', 'cn-req-1'] 
};

export const MOCK_PROJECT_CONTEXT: ProjectContext = {
  projectName: 'Nexus AI Platform',
  techStack: ['React', 'Tailwind', 'Node.js', 'Gemini API'],
  userStories: [
    'US-101: As a user, I want to filter templates by App Type so I can find relevant workflows.',
    'US-102: As a developer, I need to run code directly in the playground with context.',
    'US-103: The system should provide real-time efficiency analysis reports.'
  ]
};

const generateMockComments = (count: number): Comment[] => {
  const comments = [
    { author: 'Sarah J.', role: 'Product Manager', text: 'The output format is standard, but non-functional requirements could be more detailed.' },
    { author: 'Mike R.', role: 'Backend Dev', text: 'Code generated by Gemini 1.5 Pro is high quality, usable with minor tweaks.' },
    { author: 'Emily W.', role: 'QA Engineer', text: 'Test coverage is good, but I suggest adding some boundary condition prompts.' },
    { author: 'David K.', role: 'Frontend Dev', text: 'React component structure is clear, Tailwind classes are standard.' },
    { author: 'Lin Tao', role: 'Architect', text: 'Mermaid syntax for architecture diagrams sometimes fails, suggest emphasizing syntax checks in Prompt.' },
  ];
  return comments.slice(0, count).map((c, i) => ({ ...c, id: `cmt-${i}`, timestamp: Date.now() - i * 10000000 }));
};

// --- TRANSLATIONS ---
export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    processFlow: 'Process Flow',
    testGround: 'Test Ground',
    promptLibrary: 'Prompt Library',
    guidelines: 'AI Tools Guide',
    settings: 'Settings',
    platform: 'PLATFORM',
    welcome: 'Dashboard',
    overview: "Overview of your team's AI coding efficiency.",
    processTitle: 'AI Programming Process',
    processDesc: 'Follow the standard lifecycle to generate high-quality code.',
    shareTemplate: 'Share Template',
    promptTitle: 'Prompt Library',
    promptDesc: 'Community-driven prompts curated by role and category.',
    createPrompt: 'Create Prompt',
    searchPlaceholder: 'Search prompts...',
    aiAssistant: 'AI Assistant',
    generate: 'Generate',
    codeEditor: 'Code Editor',
    preview: 'Preview / Output',
    analyze: 'Analyze',
    run: 'Run',
    copy: 'Copy',
    requirements: 'Analysis',
    product_planning: 'Planning',
    architecture: 'System Design',
    story_creation: 'Story Creation',
    development: 'Coding',
    qa: 'QA',
    stageInput: 'Input',
    stageOutput: 'Output',
    templatePreview: 'Template Preview',
    appType: 'App Type',
    techDimensions: 'Tech Dimensions',
    projectContext: 'Project Context',
    runAiGenerate: 'Run AI Generation',
    exportAll: 'Export All',
    backToSelection: 'Back to Selection'
  },
  zh: {
    dashboard: '仪表板',
    processFlow: 'AI编程流程',
    testGround: '测试场',
    promptLibrary: '提示词库',
    guidelines: 'AI工具指南',
    settings: '设置',
    platform: '平台',
    welcome: '仪表板',
    overview: '团队AI编程效能概览',
    processTitle: 'AI编程流程',
    processDesc: '遵循标准生命周期生成高质量代码。',
    shareTemplate: '分享模板',
    promptTitle: '提示词库',
    promptDesc: '按角色和类别分类的社区驱动提示词。',
    createPrompt: '创建提示词',
    searchPlaceholder: '搜索提示词...',
    aiAssistant: 'AI 助手',
    generate: '生成',
    codeEditor: '代码编辑',
    preview: '预览 / 输出',
    analyze: '分析',
    run: '运行',
    copy: '复制',
    requirements: '需求分析',
    product_planning: '产品规划',
    architecture: '系统设计',
    story_creation: '故事创建',
    development: '编码实现',
    qa: '质量保证',
    stageInput: '输入要求',
    stageOutput: '输出预览',
    templatePreview: '报告基础信息',
    appType: '应用类型',
    techDimensions: '技术维度',
    projectContext: '当前项目上下文',
    runAiGenerate: '🤖 运行AI生成',
    exportAll: '📥 导出全部',
    backToSelection: '⬅ 返回选择',
    // 新增翻译 - 分享模板相关
    uploadDocument: '上传文档',
    aiSmartImport: 'AI 智能导入',
    generateTags: '🏷️ 生成标签',
    autoFill: '自动填充',
    aiGeneratedTags: 'AI 生成标签',
    documentPreview: '文档预览',
    processing: '处理中...',
    clearTags: '清除标签',
    templateTitle: '模板标题',
    developmentStage: '开发阶段',
    applicationType: '应用类型',
    technologyStack: '技术栈',
    description: '描述',
    inputFormat: '输入格式',
    outputFormat: '输出格式',
    supportedFeatures: '支持功能',
    promptContent: '提示词内容',
    whatShouldUserProvide: '用户应该提供什么？',
    whatWillBeGenerated: '将会生成什么？',
    createTemplate: '创建模板',
    cancel: '取消',
    projectName: '项目名称',
    keyFeatures: '主要功能',
    frontendTech: '前端技术',
    backendTech: '后端技术',
    projectContextOptional: '项目信息（可选）',
    role: '角色',
    category: '类别',
    scenarioDescription: '场景描述',
    commaSeparated: '（逗号分隔）',
    enterTemplateTitle: '输入模板标题...',
    describeWhatTemplateDoes: '描述此模板的作用...',
    enterPromptContent: '输入将发送给AI的实际提示词内容...',
    createTemplateBtn: '创建模板',
    createPromptBtn: '创建提示词'
  }
};

export const APP_TYPES = [
  { value: 'web_crud', label: 'Web CRUD 应用' },
  { value: 'mobile_app', label: '移动 App' },
  { value: 'microservice', label: '微服务/API' },
  { value: 'data_intensive', label: '数据密集型' },
  { value: 'real_time', label: '实时系统' }
];

// --- ENGLISH DATA (Simplified 6 stages) ---
export const MOCK_PROCESS_TEMPLATES_EN: ProcessTemplate[] = [
  {
    id: 'req-1',
    title: 'PRD Generator',
    stage: 'requirements',
    techStack: ['General', 'Product'],
    appType: 'web_crud',
    supports: ['User Stories', 'Acceptance Criteria'],
    description: 'Converts a rough idea into a structured PRD.',
    promptContent: 'Act as a Senior Product Manager...',
    inputFormat: 'Feature idea description',
    outputFormat: 'Markdown PRD',
    templatePreview: `# Product Requirements Document

## 1. Overview

## 2. Goals
`,
    likes: 342,
    usageCount: 1205,
    comments: generateMockComments(3),
    authorId: 'system',
    authorName: 'System Admin',
    isSystem: true,
    createdAt: Date.now()
  },
  {
    id: 'dev-1',
    title: 'React Component',
    stage: 'development',
    techStack: ['Frontend'],
    appType: 'web_crud',
    supports: ['TSX', 'Tailwind'],
    description: 'Generates a functional React component.',
    promptContent: 'Write a React component...',
    inputFormat: 'Specs',
    outputFormat: 'Code',
    templatePreview: `const Component = () => {
  return <div>Hello</div>;
}`,
    likes: 890,
    usageCount: 5400,
    comments: generateMockComments(5),
    authorId: 'system',
    authorName: 'System Admin',
    isSystem: true,
    createdAt: Date.now()
  }
];

// --- CHINESE DATA (Matching Screenshots & 6 Stages) ---
export const MOCK_PROCESS_TEMPLATES_CN: ProcessTemplate[] = [
  // 1. Requirements Analysis (需求分析)
  {
    id: 'cn-req-1',
    title: 'PRD生成器',
    stage: 'requirements',
    techStack: ['General'],
    appType: 'web_crud',
    supports: ['用户故事', '验收标准', '非功能需求'],
    description: '将初步想法转化为带用户故事和验收标准的结构化产品需求文档。',
    promptContent: `作为高级产品经理，请根据以下想法撰写PRD：
[想法描述]`,
    inputFormat: `请提供：
1. **产品名称**：(例如：Nexus AI)
2. **核心目标**：(一句话描述解决了什么问题)
3. **目标用户**：(谁会使用)
4. **关键功能列表**：(列出3-5个核心功能)`,
    outputFormat: 'Markdown格式的PRD文档',
    templatePreview: `
# [产品名称] 产品需求文档 (PRD)

| 版本 | 日期 | 作者 | 变更描述 |
|---|---|---|---|
| v1.0 | 2023-10-27 | System | 初始版本 |

## 1. 项目背景
**目标：** 本项目旨在解决...

## 2. 用户角色
- **管理员**：负责...
- **普通用户**：使用...

## 3. 功能需求
### 3.1 用户认证
- **描述**：用户可以通过邮箱注册和登录。
- **验收标准**：
  - [ ] 输入无效邮箱应提示错误。
  - [ ] 密码必须包含...
    `,
    likes: 342,
    usageCount: 1205,
    comments: generateMockComments(3),
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  },
  {
    id: 'cn-req-2',
    title: '软件项目需求分析报告模板',
    stage: 'requirements',
    techStack: ['Software Development', 'Technical Analysis'],
    appType: 'data_intensive',
    supports: ['系统架构', '技术约束'],
    description: '更侧重技术细节的软件系统、APP、小程序等开发类项目需求分析报告模板',
    promptContent: '作为系统分析师，请根据以下输入生成详细的需求分析报告...',
    inputFormat: `请提供：
1. **技术栈约束**：(例如：Java Spring Boot, MySQL)
2. **性能指标**：(例如：QPS > 1000)
3. **集成需求**：(需要对接哪些外部系统)`,
    outputFormat: '[软件名称] 需求分析报告',
    templatePreview: `## 4. 非功能性需求

### 4.1 性能要求
- **响应时间**：95%的请求应在200ms内完成。
- **并发数**：支持至少1000个并发用户。

### 4.2 安全性
- 所有API必须通过HTTPS传输。
- 敏感数据需加密存储。

### 4.3 可靠性
- 系统可用性目标为99.9%。
    `,
    likes: 150,
    usageCount: 400,
    comments: generateMockComments(1),
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now() - 100000
  },
   {
    id: 'cn-req-3',
    title: '用户画像创建器',
    stage: 'requirements',
    techStack: ['Analytics'],
    appType: 'web_crud',
    supports: ['人口统计', '用户痛点'],
    description: '基于目标受众人口统计数据生成详细用户画像',
    promptContent: '分析以下数据并生成用户画像...',
    inputFormat: '目标受众描述',
    outputFormat: '用户画像列表',
    templatePreview: `## 用户画像: [姓名]
- **年龄**: 25-35
- **职业**: 软件工程师
- **痛点**: 开发效率低...`,
    likes: 120,
    usageCount: 300,
    comments: [],
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  },

  // 2. Product Planning (产品规划)
  {
    id: 'cn-plan-1',
    title: '产品路线图生成器',
    stage: 'product_planning',
    techStack: ['Product'],
    appType: 'web_crud',
    supports: ['季度规划', '里程碑'],
    description: '根据PRD生成季度产品规划路线图',
    promptContent: '基于PRD，生成未来3个季度的路线图...',
    inputFormat: 'PRD文档内容',
    outputFormat: 'Markdown表格形式的路线图',
    templatePreview: `| 时间段 | 功能模块 | 优先级 | 关键里程碑 |
|---|---|---|---|
| Q1 | 核心功能 | P0 | MVP发布 |`,
    likes: 88,
    usageCount: 210,
    comments: [],
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  },

  // 3. System Design (系统设计)
  {
    id: 'api-design',
    title: 'API设计模板',
    stage: 'architecture', // Mapped to architecture/design
    techStack: ['Backend'],
    appType: 'microservice',
    supports: ['路径', '请求/响应', '状态码'],
    description: '生成符合 OpenAPI 规范的 RESTful 接口定义',
    promptContent: '设计OpenAPI接口...',
    inputFormat: '功能列表',
    outputFormat: 'YAML/JSON',
    templatePreview: `openapi: 3.0.0
info:
  title: Sample API`,
    likes: 200,
    usageCount: 600,
    comments: [],
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  },
  {
    id: 'db-schema',
    title: '数据库表设计模板',
    stage: 'architecture',
    techStack: ['Backend', 'Database'],
    appType: 'web_crud',
    supports: ['ER图', '字段类型', '索引优化'],
    description: '根据实体关系生成 PostgreSQL 表结构与索引建议',
    promptContent: '设计数据库Schema...',
    inputFormat: '实体描述',
    outputFormat: 'SQL DDL',
    templatePreview: `CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255)
);`,
    likes: 200,
    usageCount: 600,
    comments: [],
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  },
  {
    id: 'cn-arch-1',
    title: '微服务架构设计',
    stage: 'architecture',
    techStack: ['Backend'],
    appType: 'microservice',
    supports: ['服务拆分', '通信模式'],
    description: '为复杂系统设计微服务拆分方案',
    promptContent: '设计微服务架构...',
    inputFormat: '系统功能列表',
    outputFormat: 'Mermaid类图/架构图描述',
    templatePreview: `graph TD;
  A[Client] --> B[Gateway];
  B --> C[Auth Service];
  B --> D[User Service];`,
    likes: 200,
    usageCount: 600,
    comments: [],
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  },

  // 4. Story Creation (故事创建)
  {
    id: 'cn-story-1',
    title: '用户故事细化',
    stage: 'story_creation',
    techStack: ['Agile'],
    appType: 'web_crud',
    supports: ['INVEST原则', '验收标准'],
    description: '将功能点拆解为符合INVEST原则的用户故事',
    promptContent: '将以下功能拆解为User Stories...',
    inputFormat: '功能模块名称',
    outputFormat: '用户故事列表 (As a, I want, So that)',
    templatePreview: `- As a **User**, I want to **login**, so that I can **access my dashboard**.
  - Acceptance Criteria: ...`,
    likes: 150,
    usageCount: 450,
    comments: [],
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  },

  // 5. Coding (编码实现)
  {
    id: 'cn-dev-1',
    title: 'React+Tailwind组件生成',
    stage: 'development',
    techStack: ['Frontend'],
    appType: 'web_crud',
    supports: ['TSX', 'Hooks', 'Responsive'],
    description: '生成现代化的React功能组件，包含Props定义和样式。',
    promptContent: '使用React和Tailwind CSS编写组件...',
    inputFormat: '组件名称及功能描述 (例如：一个带有搜索功能的下拉选择器)',
    outputFormat: 'TSX代码',
    templatePreview: `export default function Button() {
  return <button className="px-4 py-2 bg-blue-500 text-white">Click</button>
}`,
    likes: 500,
    usageCount: 2000,
    comments: generateMockComments(2),
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  },

  // 6. QA (质量保证)
  {
    id: 'cn-qa-1',
    title: 'Jest单元测试生成',
    stage: 'qa',
    techStack: ['Testing'],
    appType: 'web_crud',
    supports: ['Unit Test', 'Coverage'],
    description: '为提供的代码生成全面的单元测试用例',
    promptContent: '为以下代码编写Jest测试...',
    inputFormat: '源代码',
    outputFormat: '测试代码',
    templatePreview: `describe("Button", () => {
  it("renders correctly", () => {
    render(<Button />);
  });
});`,
    likes: 180,
    usageCount: 500,
    comments: [],
    authorId: 'system',
    authorName: 'System',
    isSystem: true,
    createdAt: Date.now()
  }
];

export const MOCK_PROMPTS_EN: Prompt[] = [
    {
        id: '1',
        title: 'React Performance Optimizer',
        role: 'Frontend Dev',
        category: 'Optimization',
        scenario: 'Optimizing a slow React component with many re-renders.',
        content: `Analyze the following React component for performance bottlenecks. Suggest useMemo, useCallback, or structural changes to minimize re-renders. 

Component Code:
[PASTE CODE HERE]`,
        model: 'Gemini 1.5 Pro',
        efficiencyScore: 92,
        tags: ['react', 'performance', 'hooks'],
        likes: 45,
        comments: generateMockComments(2),
        authorId: 'system',
        authorName: 'System',
        isSystem: true,
        createdAt: Date.now()
    }
];

export const MOCK_PROMPTS_CN: Prompt[] = [
    {
        id: 'cn-1',
        title: 'React性能优化专家',
        role: 'Frontend Dev',
        category: 'Optimization',
        scenario: '优化重渲染过多的React组件',
        content: `分析以下React组件的性能瓶颈。建议使用useMemo、useCallback或结构更改以最小化重渲染。

组件代码：
[在此粘贴代码]`,
        model: 'Gemini 1.5 Pro',
        efficiencyScore: 92,
        tags: ['react', 'performance', 'hooks'],
        likes: 45,
        comments: generateMockComments(2),
        authorId: 'system',
        authorName: 'System',
        isSystem: true,
        createdAt: Date.now()
    },
    {
        id: 'cn-2',
        title: 'API接口文档生成器',
        role: 'Backend Dev',
        category: 'Documentation',
        scenario: '根据代码自动生成Swagger/OpenAPI文档',
        content: `阅读以下Node.js API路由代码，并生成标准的OpenAPI 3.0 YAML文档。

代码：
[在此粘贴代码]`,
        model: 'Gemini 1.5 Flash',
        efficiencyScore: 88,
        tags: ['api', 'documentation', 'nodejs'],
        likes: 32,
        comments: [],
        authorId: 'user-2',
        authorName: 'David Chen',
        isSystem: false,
        createdAt: Date.now() - 50000
    }
];

export const MOCK_GUIDES: Guide[] = [
  {
    id: '1',
    title: 'Prompt Engineering 101',
    category: 'Basics',
    readTime: '5 min',
    content: `# Prompt Engineering 101

Learn the basics of communicating with LLMs effectively...`
  },
  {
    id: 'cursor-1',
    title: 'Getting Started with Cursor',
    category: 'AI Tools',
    readTime: '10 min',
    toolName: 'Cursor',
    officialUrl: 'https://cursor.sh',
    content: `# Getting Started with Cursor

Cursor is an AI-first code editor built on VS Code.

## Installation
1. Go to [cursor.sh](https://cursor.sh)
2. Download for your OS.
3. Import VS Code extensions.

## Key Features
- **Cmd+K**: Edit code with AI.
- **Cmd+L**: Chat with your codebase.`
  }
];

export const MOCK_GUIDES_CN: Guide[] = [
  {
    id: 'cn-1',
    title: '提示词工程入门 101',
    category: '基础理论',
    readTime: '45 分钟',
    toolName: '提示词工程',
    isLearningPath: true,
    content: '# 提示词工程 101\n\n学习如何有效地与大语言模型沟通...\n\n## 核心原则\n1. 清晰明确\n2. 提供上下文\n3. 指定输出格式'
  },
  {
    id: 'cn-ai-learning-path',
    title: 'AI编程学习路径 - 从入门到精通',
    category: 'AI工具',
    readTime: '120 分钟',
    toolName: 'AI编程平台',
    isLearningPath: true,
    estimatedDuration: 120,
    difficulty: 'beginner',
    prerequisites: ['基础编程知识', '了解Git基本操作'],
    learningObjectives: [
      '掌握AI辅助编程的核心技能',
      '学会使用主流AI开发工具',
      '建立高效的AI编程工作流程',
      '了解AI编程的最佳实践'
    ],
    sections: [
      {
        id: 'section-1',
        title: '第一章：AI编程基础概念',
        content: `
<h2>什么是AI编程？</h2>
<p>AI编程是指利用人工智能技术（特别是大语言模型）来辅助、增强或自动化软件开发过程。它不仅仅是代码补全，而是涵盖了从需求分析到代码生成的全流程。</p>

<h2>AI编程的优势</h2>
<ul>
<li><strong>提升效率</strong>：减少重复性工作，让开发者专注于创新</li>
<li><strong>降低门槛</strong>：帮助新手快速上手复杂技术</li>
<li><strong>提高质量</strong>：AI可以提供最佳实践建议，减少bug</li>
<li><strong>持续学习</strong>：AI工具不断学习最新的编程模式和技术</li>
</ul>

<h2>常见误区</h2>
<div class="warning">
<p><strong>误区1</strong>：AI会完全取代程序员<br>
<strong>真相</strong>：AI是工具，不是替代品。它需要人来指导、验证和优化。</p>
</div>

<div class="warning">
<p><strong>误区2</strong>：AI生成的代码100%可靠<br>
<strong>真相</strong>：AI代码需要人工审查，特别是关键业务逻辑。</p>
</div>

<h2>实践练习</h2>
<p>尝试用简单的描述让AI生成一个"Hello World"程序，观察输出结果，理解AI是如何理解自然语言指令的。</p>
        `,
        duration: 20,
        order: 1,
        isCompleted: false,
        quiz: [
          {
            id: 'quiz-1-1',
            question: '以下哪项不是AI编程的优势？',
            options: [
              '提升开发效率',
              '降低编程门槛',
              '完全取代程序员',
              '提高代码质量'
            ],
            correctAnswer: 2,
            explanation: 'AI是辅助工具，不会完全取代程序员，而是增强程序员的能力。'
          },
          {
            id: 'quiz-1-2',
            question: 'AI编程的核心是什么？',
            options: [
              '让AI完全自主编程',
              '人机协作，共同创造',
              '用AI代替思考',
              '自动化所有开发工作'
            ],
            correctAnswer: 1,
            explanation: 'AI编程的核心是人与AI的协作，发挥各自优势，实现更高效的开发。'
          }
        ]
      },
      {
        id: 'section-2',
        title: '第二章：主流AI编程工具详解',
        content: `
<h2>GitHub Copilot</h2>
<p>GitHub Copilot是最早流行的AI编程助手，与VS Code深度集成。</p>

<h3>核心功能：</h3>
<ul>
<li><strong>代码自动补全</strong>：根据上下文智能生成代码建议</li>
<li><strong>注释转代码</strong>：将自然语言注释转换为代码</li>
<li><strong>多语言支持</strong>：支持数百种编程语言</li>
</ul>

<h3>使用技巧：</h3>
<ol>
<li>编写清晰的注释，告诉AI你想要什么</li>
<li>使用Tab键接受建议，Alt+[/]切换不同建议</li>
<li>定期训练AI适应你的编码风格</li>
</ol>

<h2>Cursor编辑器</h2>
<p>Cursor是专为AI编程设计的代码编辑器，提供更强大的AI交互能力。</p>

<h3>特色功能：</h3>
<ul>
<li><strong>Cmd+K</strong>：选中代码进行AI编辑</li>
<li><strong>Cmd+L</strong>：与AI对话，询问代码相关问题</li>
<li><strong>@Codebase</strong>：引用整个代码库作为上下文</li>
</ul>

<h2>ChatGPT/GPT-4</h2>
<p>通用AI助手，适用于复杂的编程问题解决和架构设计。</p>

<h3>最佳使用场景：</h3>
<ul>
<li>算法设计和优化</li>
<li>系统架构设计</li>
<li>复杂bug调试</li>
<li>技术方案评估</li>
</ul>

<h2>工具对比</h2>
<table>
<thead>
<tr><th>工具</th><th>适用场景</th><th>优势</th><th>局限</th></tr>
</thead>
<tbody>
<tr><td>GitHub Copilot</td><td>日常编码</td><td>IDE集成度高</td><td>功能相对单一</td></tr>
<tr><td>Cursor</td><td>复杂项目</td><td>功能强大</td><td>需要适应期</td></tr>
<tr><td>ChatGPT</td><td>问题解决</td><td>通用性强</td><td>无代码环境</td></tr>
</tbody>
</table>
        `,
        duration: 30,
        order: 2,
        isCompleted: false,
        quiz: [
          {
            id: 'quiz-2-1',
            question: 'Cursor编辑器的核心快捷键是什么？',
            options: [
              'Ctrl+S',
              'Cmd+K',
              'F5',
              'Ctrl+C'
            ],
            correctAnswer: 1,
            explanation: 'Cmd+K是Cursor的核心快捷键，用于选中代码进行AI编辑。'
          },
          {
            id: 'quiz-2-2',
            question: '以下哪个场景最适合使用ChatGPT？',
            options: [
              '快速代码补全',
              'IDE内实时编辑',
              '复杂算法设计',
              '简单的语法补全'
            ],
            correctAnswer: 2,
            explanation: 'ChatGPT在复杂算法设计和问题解决方面表现优秀，适合处理需要深度思考的编程问题。'
          }
        ]
      },
      {
        id: 'section-3',
        title: '第三章：AI编程最佳实践',
        content: `
<h2>提示词工程核心技巧</h2>

<h3>1. 明确性原则</h3>
<p>提供清晰、具体的指令，避免模糊表述。</p>

<h4>❌ 不佳示例：</h4>
<blockquote>
<p>写一个函数</p>
</blockquote>

<h4>✅ 优秀示例：</h4>
<blockquote>
<p>创建一个TypeScript函数，名为calculateTotal，接受一个Product对象数组，返回总价。函数需要：1. 处理空数组情况 2. 支持小数点精度 3. 包含类型注解 4. 添加错误处理</p>
</blockquote>

<h3>2. 上下文原则</h3>
<p>提供足够的背景信息，让AI理解你的需求。</p>

<h4>关键信息包括：</h4>
<ul>
<li>项目技术栈（React、Vue、Node.js等）</li>
<li>编码规范和风格要求</li>
<li>性能和安全要求</li>
<li>相关依赖和约束</li>
</ul>

<h3>3. 结构化原则</h3>
<p>使用结构化的提示词格式，提高输出质量。</p>

<h4>CRISPE框架：</h4>
<ul>
<li><strong>C</strong>ontext（上下文）：提供背景信息</li>
<li><strong>R</strong>ole（角色）：设定AI的角色身份</li>
<li><strong>I</strong>nstruction（指令）：明确任务要求</li>
<li><strong>S</strong>teps（步骤）：拆解执行步骤</li>
<li><strong>P</strong>ersona（人格）：设定输出风格</li>
<li><strong>E</strong>xamples（示例）：提供输入输出样例</li>
</ul>

<h2>代码审查要点</h2>
<h3>安全性检查</h3>
<ul>
<li>检查SQL注入、XSS等安全漏洞</li>
<li>验证输入处理和边界条件</li>
<li>确保敏感信息不被泄露</li>
</ul>

<h3>性能评估</h3>
<ul>
<li>分析时间复杂度和空间复杂度</li>
<li>检查是否有不必要的计算</li>
<li>评估内存使用和资源消耗</li>
</ul>

<h3>可维护性</h3>
<ul>
<li>代码结构是否清晰易懂</li>
<li>变量和函数命名是否规范</li>
<li>是否遵循团队编码规范</li>
</ul>

<h2>持续改进策略</h2>
<ol>
<li><strong>建立提示词库</strong>：积累和复用高效的提示词</li>
<li><strong>定期评估</strong>：回顾AI生成代码的质量和效率</li>
<li><strong>团队协作</strong>：分享最佳实践和经验教训</li>
<li><strong>保持学习</strong>：关注AI工具的最新发展和功能更新</li>
</ol>
        `,
        duration: 25,
        order: 3,
        isCompleted: false,
        quiz: [
          {
            id: 'quiz-3-1',
            question: 'CRISPE框架中的"I"代表什么？',
            options: [
              'Implementation',
              'Instruction',
              'Interaction',
              'Information'
            ],
            correctAnswer: 1,
            explanation: '在CRISPE框架中，I代表Instruction（指令），用于明确告诉AI需要执行的具体任务。'
          },
          {
            id: 'quiz-3-2',
            question: 'AI生成代码审查时，哪个方面最重要？',
            options: [
              '代码长度最短',
              '安全性和性能',
              '代码格式美观',
              '语法绝对正确'
            ],
            correctAnswer: 1,
            explanation: '安全性和性能是最重要的考量因素，因为它们直接影响应用的质量和用户体验。'
          }
        ]
      },
      {
        id: 'section-4',
        title: '第四章：实战项目演练',
        content: `
<h2>项目一：AI辅助开发Todo应用</h2>

<h3>项目概述</h3>
<p>使用AI工具从零开始开发一个完整的Todo应用，涵盖前端、后端和数据库设计。</p>

<h3>步骤1：需求分析</h3>
<p>使用AI进行需求分析和用户故事设计：</p>

<h4>提示词示例：</h4>
<blockquote>
<p>作为产品经理，请帮我设计一个Todo应用的产品需求文档。需要包含：1. 用户角色定义 2. 核心功能列表 3. 用户故事 4. 验收标准</p>
</blockquote>

<h3>步骤2：技术架构设计</h3>
<p>利用AI设计系统架构：</p>

<h4>提示词示例：</h4>
<blockquote>
<p>作为系统架构师，为Todo应用设计技术方案。技术栈要求：前端使用React+TypeScript，后端使用Node.js+Express，数据库使用MongoDB。请提供：1. 系统架构图 2. API设计 3. 数据库模型 4. 安全考虑</p>
</blockquote>

<h3>步骤3：代码实现</h3>
<p>使用AI生成基础代码结构：</p>

<h4>前端组件生成：</h4>
<blockquote>
<p>创建一个React TypeScript组件，用于显示Todo列表。组件需要：1. 支持添加、删除、标记完成 2. 使用本地存储持久化数据 3. 包含过滤功能（全部/进行中/已完成） 4. 响应式设计，适配移动端</p>
</blockquote>

<h4>后端API开发：</h4>
<blockquote>
<p>设计RESTful API用于Todo管理，包含以下端点：GET /api/todos、POST /api/todos、PUT /api/todos/:id、DELETE /api/todos/:id。使用Express.js和MongoDB，包含错误处理和数据验证。</p>
</blockquote>

<h3>步骤4：测试和优化</h3>
<p>使用AI生成测试用例：</p>

<h4>单元测试提示词：</h4>
<blockquote>
<p>为Todo应用的React组件编写Jest测试用例。需要测试：1. 组件渲染正确性 2. 添加Todo功能 3. 删除Todo功能 4. 标记完成功能 5. 过滤功能</p>
</blockquote>

<h2>项目二：AI优化现有代码</h2>

<h3>场景描述</h3>
<p>提供一个性能不佳的现有代码，使用AI进行优化。</p>

<h3>优化流程：</h3>
<ol>
<li><strong>代码分析</strong>：使用AI识别性能瓶颈和改进点</li>
<li><strong>重构建议</strong>：获取具体的优化建议和实现方案</li>
<li><strong>代码重写</strong>：生成优化后的代码</li>
<li><strong>性能测试</strong>：验证优化效果</li>
</ol>

<h3>示例优化场景：</h3>
<ul>
<li>React组件渲染优化</li>
<li>数据库查询优化</li>
<li>算法性能提升</li>
<li>内存使用优化</li>
</ul>

<h2>项目三：AI辅助技术决策</h2>

<h3>决策场景</h3>
<p>在项目开发中遇到技术选型问题时，使用AI提供决策支持。</p>

<h4>示例提示词：</h4>
<blockquote>
<p>我们需要为新的电商平台选择前端框架。选项包括React、Vue、Angular。考虑因素：1. 团队技术熟悉度 2. 开发效率 3. 性能表现 4. 生态系统成熟度 5. 长期维护成本。请提供详细的对比分析和建议。</p>
</blockquote>

<h3>实践成果评估</h3>
<ul>
<li>记录开发时间的节省情况</li>
<li>评估代码质量改进程度</li>
<li>分析团队成员学习曲线</li>
<li>总结成功经验和失败教训</li>
</ul>
        `,
        duration: 45,
        order: 4,
        isCompleted: false,
        quiz: [
          {
            id: 'quiz-4-1',
            question: '在AI辅助开发Todo应用时，第一步应该做什么？',
            options: [
              '直接写代码',
              '需求分析',
              '部署上线',
              '性能优化'
            ],
            correctAnswer: 1,
            explanation: '需求分析是软件开发的第一步，明确需求才能设计出合适的技术方案。'
          },
          {
            id: 'quiz-4-2',
            question: 'AI代码优化流程的正确顺序是？',
            options: [
              '优化→分析→重写→测试',
              '分析→优化→重写→测试',
              '测试→分析→优化→重写',
              '重写→优化→分析→测试'
            ],
            correctAnswer: 1,
            explanation: '正确的优化流程是：先分析问题，然后制定优化方案，接着重写代码，最后进行测试验证。'
          }
        ]
      }
    ],
    tags: ['学习路径', 'AI编程', '实战项目', '最佳实践']
  },
  {
    id: 'cn-cursor',
    title: 'Cursor 编辑器安装与使用',
    category: 'AI工具',
    readTime: '10 分钟',
    toolName: 'Cursor',
    officialUrl: 'https://cursor.sh',
    tags: ['IDE', 'AI编程', '效率'],
    content: `
# Cursor 编辑器指南

Cursor 是一款基于 VS Code 构建的 AI 原生代码编辑器，旨在通过 AI 大幅提升编码效率。

## 1. 安装指南
1. 访问官网 [cursor.sh](https://cursor.sh)
2. 点击 "Download" 下载对应系统版本（Windows/Mac/Linux）。
3. 安装后首次启动，选择 "Import VS Code Extensions" 可一键迁移插件和配置。

## 2. 核心功能
- **Cmd+K (Ctrl+K)**: 在编辑器中直接生成或修改代码。选中一段代码，按 Ctrl+K，输入"重构此函数"即可。
- **Cmd+L (Ctrl+L)**: 打开 AI 侧边栏聊天。可以询问"解释这个文件做了什么"或"如何修复这个 bug"。
- **@Codebase**: 在聊天中输入 @ 符号，可以引用整个代码库、特定文件或文档作为上下文。

## 3. 最佳实践
- 始终在 Prompt 中明确你的需求。
- 利用 @ 符号精准投喂上下文。
- 在 "Cursor Settings" 中配置自己的 OpenAI Key (可选) 或使用 Cursor 自带的额度。
    `
  },
  {
    id: 'cn-copilot',
    title: 'GitHub Copilot 配置全攻略',
    category: 'AI工具',
    readTime: '8 分钟',
    toolName: 'GitHub Copilot',
    officialUrl: 'https://github.com/features/copilot',
    tags: ['插件', '补全', 'GitHub'],
    content: `
# GitHub Copilot 指南

GitHub Copilot 是您的 AI 结对程序员，可在您编写代码时提供自动补全建议。

## 1. 订阅与安装
1. 访问 [GitHub Copilot](https://github.com/settings/copilot) 页面并开启订阅（个人版或企业版）。
2. 打开 VS Code，在插件市场搜索 "GitHub Copilot" 并安装。
3. 安装完成后，点击右下角的 GitHub 图标登录您的账号。

## 2. 使用技巧
- **自动补全**: 开始输入代码，Copilot 会显示灰色建议。按 \`Tab\` 键接受建议。
- **多选一**: 如果有多个建议，按 \`Alt + ]\` 或 \`Alt + [\` 切换。
- **注释驱动开发**: 编写清晰的注释，例如 \`// 用于计算斐波那契数列的函数\`，然后换行等待 Copilot 生成代码。

## 3. 常见问题
- **不显示建议**: 检查网络连接，或确认右下角 Copilot 图标是否处于启用状态。
    `
  },
  {
    id: 'cn-gemini',
    title: 'Gemini API 开发者接入指南',
    category: 'AI工具',
    readTime: '15 分钟',
    toolName: 'Google Gemini',
    officialUrl: 'https://ai.google.dev/',
    tags: ['API', 'LLM', 'Google'],
    content: `
# Google Gemini API 接入指南

Gemini 是 Google 最强大的多模态模型。本指南介绍如何获取 API Key 并进行简单的调用。

## 1. 获取 API Key
1. 访问 [Google AI Studio](https://aistudio.google.com/)。
2. 点击 "Get API key"。
3. 点击 "Create API key in new project"。
4. 复制生成的 API Key (注意保密)。

## 2. 快速开始 (Node.js)
安装 SDK:
\`\`\`bash
npm install @google/genai
\`\`\`

代码示例:
\`\`\`javascript
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
const response = await ai.models.generateContent({
  model: 'gemini-2.5-flash',
  contents: 'Explain AI in 50 words.',
});

console.log(response.text);
\`\`\`

## 3. 费用说明
- 目前 Gemini Flash 版本提供免费层级（有速率限制）。
- 生产环境建议绑定计费账户以获得更高额度。
    `
  }
];
